version: 1.1.0.{build}
image: Visual Studio 2017

configuration:
  - Release

platform:
  - x86

before_build:
  # "1.1.0.76" -> "1_1_0_76"
  - set ARTIFACT_VERSION=%APPVEYOR_BUILD_VERSION:.=_%
  # init submodule
  - cd ext\cereal
  - git submodule update -i
  - git checkout v1.2.2
  - cd ..\..

build:
  project: CompactMeter.sln

after_build:
  - copy Release\CompactMeter.exe .
  - 7z a CompactMeter_v%ARTIFACT_VERSION%.zip CompactMeter.exe README.md

artifacts:
#  - path: 'Release\CompactMeter.exe'
  - path: CompactMeter_v$(ARTIFACT_VERSION).zip
