version: 1.2.0.{build}
image: Visual Studio 2017

configuration:
  - Release

platform:
  # ここで x64 も指定すると個別の zip ファイルに分かれてしまうので
  # x64 版は after_build で生成する
  - x86

install:
  # init submodule
  - cd ext\cereal
  - git submodule update -i
  - git checkout v1.2.2
  - cd ..\..

before_build:
  # "1.1.0.76" -> "1_1_0_76"
  - set ARTIFACT_VERSION=%APPVEYOR_BUILD_VERSION:.=_%

build_script:
  - 100_build_exe.bat

after_build:
  # packaging
  - 200_packaging.bat

artifacts:
  - path: packaging/CompactMeter_v$(ARTIFACT_VERSION).zip
