version: 1.2.0.{build}
image: Visual Studio 2017

configuration:
  - Release

platform:
  # ここで x64 も指定すると個別の zip ファイルに分かれてしまうので
  # x64 版は after_build で生成する
  - x86

install:
  # init submodule
  - cd ext\cereal
  - git submodule update -i
  - git checkout v1.2.2
  - cd ..\..

before_build:
  # "1.1.0.76" -> "1_1_0_76"
  - set ARTIFACT_VERSION=%APPVEYOR_BUILD_VERSION:.=_%

build:
  project: CompactMeter.sln

after_build:
  # 64bit build
  - msbuild "%APPVEYOR_BUILD_FOLDER%\CompactMeter.sln" /p:Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  # packaging
  - copy Release\CompactMeter.exe .
  - copy Release\register.exe .
  - copy x64\Release\CompactMeter_64.exe .
  - 7z a CompactMeter_v%ARTIFACT_VERSION%.zip CompactMeter.exe CompactMeter_64.exe register.exe README.md

artifacts:
  - path: CompactMeter_v$(ARTIFACT_VERSION).zip
