version: 1.1.0.{build}
image: Visual Studio 2017

configuration:
  - Release

platform:
  - x86

before_build:
  - set ARTIFACT_VERSION=%APPVEYOR_BUILD_VERSION:.=_%

artifacts:
#  - path: 'Release\CompactMeter.exe'
  - path: CompactMeter_$(ARTIFACT_VERSION).zip

after_build:
  - copy Release\CompactMeter.exe .
  - 7z a CompactMeter_%ARTIFACT_VERSION%.zip CompactMeter.exe README.md
